Fix build for hipclang
ROCmSoftwarePlatform/rocBLAS pull request #751
Opened 2019-10-15 22:43 UTC by AlexBrownAMD

Function definitions in hpp files need inline.
Templated functions with multiple template params need HIP_KERNEL_NAME.
Fix rotm kernel templating.

2019-10-15 23:01 UTC, daineAMD approved these changes
Looks like you might need to do a clang format for jenkins, looks good to me otherwise.

2019-10-15 23:34 UTC, leekillough commented
> Function definitions in hpp files need inline.

... or `static`, `constexpr` or `template`.

Function or class templates can be redefined if the same tokens are used in each translation unit. You do not need `inline` in every case.

Variable templates must be `inline` or `static` if defined in multiple header files. `constexpr` no longer implies `static` for variable templates (this is a retroactive language defect fix for C++14).

> Templated functions with multiple template params need HIP_KERNEL_NAME.

Correction:  **Macro arguments with commas inside of them, such as in template argument lists, must be parenthesized to avoid syntactic ambiguity.**

`HIP_KERNEL_NAME` is a no-op which just adds confusion. You can just use parentheses:
```
 hipLaunchKernelGGL((dot_kernel_part1<NB, CONJ, T>),
```

2019-10-15 23:40 UTC, leekillough requested changes
Use simple parentheses around macro arguments to disambiguate nested commas, instead of using the confusing `HIP_KERNEL_NAME` macro..

2019-10-16 15:36 UTC, AlexBrownAMD commented
> Function or class templates can be redefined if the same tokens are used in each translation unit. You do not need `inline` in every case.

This does not appear to be the case in hipclang: functions defined in headers without a qualifier like inline cause "multiple definition" errors at link time.

> `HIP_KERNEL_NAME` is a no-op which just adds confusion. You can just use parentheses:

Pushed an update removing HIP_KERNEL_NAME. Though, I personally think having it there makes the code more clear and readable. It calls attention to the fact that the parentheses are there for a reason.

2019-10-16 23:25 UTC, leekillough commented
> > Function or class templates can be redefined if the same tokens are used in each translation unit. You do not need `inline` in every case.
> 
> This does not appear to be the case in hipclang: functions defined in headers without a qualifier like inline cause "multiple definition" errors at link time.

Templates should be an exception, if they are defined with the same tokens, such as including the same header with the same template definition multiple times:

> There can be more than one definition in a program of each of the following: class type, enumeration type, inline function, inline variable (since C++17), class template, **non-static function template**, static data member of a class template, member function of a class template, partial template specialization, concept (since C++20), as long as all of the following is true: 
> * each definition appears in a different translation unit 
> ...
> * each definition consists of the same sequence of tokens (typically, appears in the same header file)
> ...
 > * the language linkage is the same (e.g. the include file isn't inside an extern "C" block) 
> ...
> * if the definition is for a template, then all these requirements apply to both names at the point of definition and dependent names at the point of instantiation 
>
> If all these requirements are satisfied, the program behaves as if there is only one definition in the entire program. Otherwise, the behavior is undefined. 
>
> https://en.cppreference.com/w/cpp/language/definition

**Non-templated** functions need to be `inline`, `static` or `constexpr`, or in an unnamed namespace (which isn't usually a good idea in headers), to appear in multiple translation units. I usually use `static` if there's no benefit to inlining it and I really want it defined in a header file; otherwise I use `inline`. If the function is simple and can appear in a constant expression, I use `constexpr`, which implies `inline`.

(If a function template is declared `static` in a header file and appears in multiple compilation units, then it is internal to each compilation unit, so there is no conflict between them, no multiple definition, and no requirement that they have the same token sequence.)

> > `HIP_KERNEL_NAME` is a no-op which just adds confusion. You can just use parentheses:
> 
> Pushed an update removing HIP_KERNEL_NAME. Though, I personally think having it there makes the code more clear and readable. It calls attention to the fact that the parentheses are there for a reason.

I don't think it makes it any clearer -- it sounds like a macro which has to be called to "get" the name of a kernel from something passed to it. We used to use "get kernel name" type functions in GEMM, for a different purpose (to get the names of low-level Tensile kernels which get called for particular GEMM arguments), but they are slowly being obsoleted.

Also, is `HIP_KERNEL_NAME` defined by HIP, or by us? We should not misappropriate `HIP_*` names.

2019-10-17 00:13 UTC, leekillough approved these changes
Approved, but with the caution to keep in mind that there are multiple ways of defining functions in header files `#include`'d in multiple compilation units:

1. `inline`
2. `constexpr` (implies `inline`)
3. `static`
4. `template` (does not require `inline` or `static`)
5. Combinations of the above
6. (Not recommended.) `#define` macros to change the name in each compilation unit, use unnamed namespaces, etc.

Which one to use for a particular function, may depend on the circumstances.

2019-10-17 00:40 UTC, leekillough commented
Looks like some `clang-format`ting issues in`library/src/blas3/Tensile/gemm.hpp`

2019-10-17 16:12 UTC, AlexBrownAMD commented
Whoops, somehow missed gemm.hpp in my clang-format pass - got it updated.

2019-10-17 16:23 UTC, merged